# Generated by Django 3.0.2 on 2020-01-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200112_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Member', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(default='L', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(default='No Team', max_length=100),
        ),
    ]
