# Generated by Django 3.0.2 on 2020-01-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
